#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jellyfin-session-kicker'
        image: 'wardpearce/session-kicker'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}:/data'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          JELLYFIN_API_KEY: ''
          JELLYFIN_API_URL: ''

          DONT_KICK_ITEM_TYPE: 'movie'
          CHECK_DELAY_IN_SECONDS: '10.0'
          MESSAGE_TIME_IN_MILLI: '60000'
          MAX_WATCH_TIME_IN_SECONDS: '50.0'

          # Leave blank to disable
          ITEM_ID_ON_SESSION_KICKED: ''

          WATCH_TIME_OVER_MSG: 'You have used up your watch time.'
          NOT_WHITELISTED_MSG: 'You are not whitelisted for unlimited watch time.'

          RESET_AFTER_IN_HOURS: '24.0'

          HTTP_HOST: 'session_kicker'
          HTTP_PORT: '80'

          MONGO_DB: 'session_timer'
          MONGO_HOST: 'session_kicker_mongo'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started

    - name: 'Stopping {{pgrole}}. Go configure Environment Variables in Portainer.'
      docker_container:
        name: '{{pgrole}}'
        state: stopped
