#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jellyfin-intro-scanner'
        image: 'ghcr.io/mueslimak3r/jellyfin-intro-scanner:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/jellyfin-intro-detection:/app/config'
          - '/mnt:/mnt'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          JELLYFIN_URL: 'http://jellyfin:8096'
          JELLYFIN_USERNAME: 'root'
          JELLYFIN_PASSWORD: 'password'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started

    - name: 'Stopping {{pgrole}}. Go configure Environment Variables in Portainer.'
      docker_container:
        name: '{{pgrole}}'
        state: stopped
