#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'paycord'
        image: 'wardpearce/paycord'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          DISCORD_CLIENT_ID="..."
          DISCORD_CLIENT_SECRET="..."
          DISCORD_BOT_TOKEN="..."
          DISCORD_GUILD_ID="..."
          ROOT_DISCORD_IDS="...,..."
          STRIPE_WEBHOOK_SECRET="..."
          STRIPE_API_KEY="..."
          LOGO_URL="https://i.imgur.com/d5SBQ6v.png"
          PAGE_NAME="Karna.ge"

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started

    - name: 'Stopping {{pgrole}}. Go configure Environment Variables in Portainer.'
      docker_container:
        name: '{{pgrole}}'
        state: stopped
